name: SE333_CI
on:
  push:
    branches:
      - main

jobs:
  SE333_CI_JOB:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v4

      - name: setupJava
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64

      - name: Install Linter (Checkstyle)
        ##TODO
        run: |
          sudo apt-get update
          sudo apt-get install -y checkstyle 



      - name: Run Checkstyle
        ##TODO
        run: mvn checkstyle:checkstyle -Dcheckstyle.failOnViolation=false


      - name: Upload Checkstyle Result
        ##TODO
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-result
          path: target/checkstyle-result.xml

      - name: Run Maven Test
        ##TODO
        run: mvn test

      - name: Jacoco Report
        ##TODO
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/index.html

      - name: List Build Artifacts
        run: ls -l target/
